apiVersion: v1
kind: Service
metadata:
  namespace: crawler-bot
  name: bugsearch-service
spec:
  selector:
    app: bugsearch
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082