apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crawler-bot
  name: bugsearch
  labels:
    app: bugsearch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bugsearch
  template:
    metadata:
      labels:
        app: bugsearch
    spec:
      containers:
      - name: bugsearch
        image: acrworkflow1684607545542.azurecr.io/bugsearch
        ports:
        - containerPort: 8082
        resources:
              limits:
                cpu: 500m
              requests:
                cpu: 200m