apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-kubernetes-service
  labels:
    app: azure-kubernetes-service
  namespace: crawler-bot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azure-kubernetes-service
  template:
    metadata:
      labels:
        app: azure-kubernetes-service
    spec:
      containers:
        - name: azure-kubernetes-service
          image: acrworkflow1684607545542.azurecr.io/image-workflow-1684607545542:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password
            - name: DB_CONN_STRING
              valueFrom: 
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
