apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: crawler-bot
  name: crawler-bot-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: api.bugsearch.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: azure-kubernetes-service
                port:
                  number: 80