apiVersion: v1
kind: Service
metadata:
  name: azure-kubernetes-service
  namespace: namespace-workflow-1684607545542
spec:
  type: LoadBalancer
  selector:
    app: azure-kubernetes-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080